# Generated by Django 4.1.2 on 2022-11-29 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('food_unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_name', models.CharField(max_length=30)),
                ('nutrient_unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('condition', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Serum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serum_name', models.CharField(max_length=30)),
                ('serum_unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Serum_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serum_entry_date', models.DateField()),
                ('serum_entry_time', models.TimeField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.person')),
            ],
        ),
        migrations.CreateModel(
            name='Serum_Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serum_measure_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('serum_entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.serum_entry')),
                ('serum_nutrient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.serum')),
            ],
        ),
        migrations.CreateModel(
            name='Journal_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_date', models.DateField()),
                ('journal_time', models.TimeField()),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='journals.meal')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.person')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_nutrient_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.food')),
                ('nutrient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.nutrient')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_journal_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.food')),
                ('journal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.journal_entry')),
            ],
        ),
    ]
