# Generated by Django 4.1.2 on 2022-12-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_unit',
        ),
        migrations.RemoveField(
            model_name='food_journal',
            name='g_protein',
        ),
        migrations.RemoveField(
            model_name='food_journal',
            name='mg_phosphorus',
        ),
        migrations.RemoveField(
            model_name='food_journal',
            name='mg_potassium',
        ),
        migrations.RemoveField(
            model_name='food_journal',
            name='mg_sodium',
        ),
        migrations.AddField(
            model_name='food',
            name='g_protein',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='food',
            name='mg_phosphorus',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='food',
            name='mg_potassium',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='food',
            name='mg_sodium',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='food_journal',
            name='servings',
            field=models.IntegerField(default=0),
        ),
    ]
