# Generated by Django 4.1.2 on 2022-11-30 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_entry',
            name='journal_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='journal_entry',
            name='journal_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
