# Generated by Django 4.1.2 on 2022-11-30 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_alter_journal_entry_journal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_entry',
            name='journal_time',
            field=models.TimeField(default=datetime.datetime.today),
        ),
    ]
