# Generated by Django 4.1.2 on 2022-11-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_alter_journal_entry_journal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_entry',
            name='journal_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
